server:
  port: 8088
  servlet:
    context-path: /userProject/controller
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.21.13.14:3306/demodb
    username: demo
    password: demo123456