server:
  port: 8011
  
info:
  description: spring boot actuator
  
management:  endpoints:    web:      exposure:        include: "*"  endpoint:    shutdown:      enabled: true
    loggers:      enabled: false