server:
  port: 8011
  
info:
  description: spring boot actuator
  
management:  endpoints:    web:      exposure:        include: "*"    enabled-by-default: false
  endpoint:    shutdown:      enabled: true
  